# Generated by Django 3.2.6 on 2021-10-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211024_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
